
# Site settings
title: "Suhaib Khan"
description: "Software Engineer, Open Source Enthusiast"
baseurl: "" # e.g. /blog
url: "http://suhaibkhan.github.io"

author:
  name: "Suhaib Khan"
  email: suhaibkhan@gmail.com
  github_url:  "https://github.com/suhaibkhan"
  linkedin_url: "https://in.linkedin.com/in/suhaibkhans"
  facebook_url: "https://www.facebook.com/suhaibkhan.s"
  googleplus_url: "https://plus.google.com/117492144186891134145"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
      author: "Suhaib Khan"


# Build settings
permalink: /:year/:month/:title.html
markdown: kramdown
highlighter: rouge
timezone: Asia/Calcutta

kramdown:
  # Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
